using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.SceneManagement;

public class TutorialManager : MonoBehaviour
{
    [SerializeField] private GameObject TutorialCanvas;
    [SerializeField] private TMP_Text TutorialText;
    [SerializeField] private TMP_Text BossUItext;
    [SerializeField] private TMP_Text PlayerHPUIText;
    [SerializeField] private TMP_Text PlayerSkillText;
    [SerializeField] private TMP_Text TaskText;
    [SerializeField] private TMP_Text inputText;
    [SerializeField] private GameObject TaskBox;
    [SerializeField] private GameObject Player;
    [SerializeField] private GameObject BossManager;
    [SerializeField] private GameObject ProjectileManager;
    [SerializeField] private GameObject MainGameSceneManager;
    private MainGameSceneManage MainGameSceneManage;
    private PlayerMovementTutorial PlayerMovementTutorial;
    private BossManagerTutorial BossManagerTutorial;
    private TutorialProjetileManager TutorialProjetileManager;
    private TutorialCheckManager TutorialCheckManager;
    private GameObject GameManager;
    private TimeManager TimeManager;
    private float BossHealth;
    void Start()
    {
        TutorialCheckManager = FindObjectOfType<TutorialCheckManager>();
        MainGameSceneManage = MainGameSceneManager.GetComponent<MainGameSceneManage>();
        TutorialProjetileManager = ProjectileManager.GetComponent<TutorialProjetileManager>();
        BossManagerTutorial = BossManager.GetComponent<BossManagerTutorial>();
        PlayerMovementTutorial = Player.GetComponent<PlayerMovementTutorial>();
        GameManager = GameObject.FindGameObjectWithTag("GameManager");
        TimeManager = GameManager.GetComponent<TimeManager>();
        TimeManager.isTutorial = true;
        BossUItext.text = string.Empty;
        PlayerHPUIText.text = string.Empty;
        PlayerSkillText.text = string.Empty;
        TaskText.text = string.Empty;
        TaskBox.SetActive(false);
        StartCoroutine(Tutorial());
    }

    IEnumerator Tutorial()
    {
        yield return new WaitForSeconds(1f);
        TutorialCanvas.SetActive(true);
        TutorialText.text = "Welcome To INFECTION\nインフェクションへようこそ";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "Here is a Tutorial to teach you about the basic controls\nここは基本操作を学ぶためのチュートリアルです";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "First,Let's Start from The Movement\n最初は移動です";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "For Keyboard:Arrow Key\nFor Controller:Left Joystick\nキーボード：矢印キー\nコントローラー：左ジョイスティック";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "Let's try to move around\n試しに動かしてみよう";
        yield return new WaitForSeconds(3f);
        TutorialCanvas.SetActive(false);
        PlayerMovementTutorial.canMove = true;
        TaskText.text = "Task:\nMove Around\nタスク：\n試しに動かしてみよう";
        inputText.text = "For Keyboard:Arrow Key\nFor Controller:Left Joystick\nキーボード：矢印キー\nコントローラー：左ジョイスティック";
        yield return new WaitUntil(() => PlayerMovementTutorial.Moved == true);
        TaskBox.SetActive(true);
        yield return new WaitForSeconds(3f);
        TaskBox.SetActive(false);
        TaskText.text = string.Empty;
        inputText.text = string.Empty;
        Player.transform.position = PlayerMovementTutorial.PlayerOriginposition;
        PlayerMovementTutorial.canMove = false;
        TutorialCanvas.SetActive(true);
        TutorialText.text = "Great!\n素晴らしい〜";
        yield return new WaitForSeconds(3f);
        TutorialText.text = "Next,Let me introduce the enemy\n次はボスの紹介です";
        yield return new WaitForSeconds(3f);
        TutorialCanvas.SetActive(false);
        BossManagerTutorial.SpawnBoss();
        yield return new WaitForSeconds(2f);
        TutorialCanvas.SetActive(true);
        TutorialText.text = "In this game,We only have one Boss\nこのゲームは一つのボスだけがある";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "During the game,it will go around Randomly\nボスはランダムに動き回る";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "But for this Tutorial,it will just stay uptop\nただし、今回はチュートリアルなのでボスは一番上に固定する";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "Next,How to Attack the Boss\n次はボスへの攻撃方法を紹介する";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "In this game,we don't have a button for the normal attack\nこのゲームでは、通常攻撃ボタンがありません";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "To perform a normal attack,just touch the boss\nその代わりボスに接近する";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "Get close to the Boss and it will automatically perform a normal attack\nボスに接近すると自動で攻撃が出る";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "Touching the Boss doesn't do damage to us\nkeep touching the boss to reach the maximum DPS\nボスに触れてもダメージはないので、\nボスに触り続けることでたくさんのダメージを与えることができる";
        yield return new WaitForSeconds(6f);
        TutorialText.text = "Try it out\nでは、ダメージを与えてみましょう";
        yield return new WaitForSeconds(3f);
        TutorialText.text = string.Empty;
        TutorialCanvas.SetActive(false);
        PlayerMovementTutorial.canMove = true;
        TaskText.text = "Task:\nGet close to the Boss\nDo some damage\nタスク：\nボスに近づき、\nダメージを与えましょう";
        yield return new WaitUntil(() => BossHealth >= 60f);
        TaskBox.SetActive(true);
        yield return new WaitForSeconds(3f);
        TaskBox.SetActive(false);
        TaskText.text = string.Empty;
        Player.transform.position = PlayerMovementTutorial.PlayerOriginposition;
        PlayerMovementTutorial.canMove = false;
        TutorialCanvas.SetActive(true);
        BossUItext.text = "This is the Boss Health Bar\nこれは攻略度のゲージです";
        yield return new WaitForSeconds(4f);
        BossUItext.text = "If you do enough damage to the Boss\nThe Health Bar will increase by percentage\nボスに一定ダメージを与えると、\nゲージが増加する";
        yield return new WaitForSeconds(5f);
        BossUItext.text = "If it went to 100%,GameClear\nゲージが100%になるとゲームクリアです";
        yield return new WaitForSeconds(3f);
        BossUItext.text = string.Empty;
        TutorialCanvas.SetActive(false);
        TutorialProjetileManager.spawnSword();
        yield return new WaitForSeconds(1.7f);
        MainGameSceneManage.isTutorialPause = true;
        Time.timeScale = 0;
        TutorialCanvas.SetActive(true);
        TutorialText.text = "This is a SlowAttack make from the Boss\nこれはボスによる攻撃です";
        yield return new WaitForSecondsRealtime(4f);
        TutorialText.text = "if it hit us,it will do damage to us\nこれに当たるとダメージを受ける";
        yield return new WaitForSecondsRealtime(3f);
        TutorialText.text = string.Empty;
        MainGameSceneManage.isTutorialPause = false;
        Time.timeScale = 1;
        TutorialCanvas.SetActive(false);
        yield return new WaitForSeconds(2f);
        TutorialCanvas.SetActive(true);
        PlayerHPUIText.text = "This is our Health Bar\nこれは体力ゲージです";
        yield return new WaitForSeconds(4f);
        PlayerHPUIText.text = "If it went to 0,GameOver\n0になるとゲームオーバーです";
        yield return new WaitForSeconds(3f);
        TutorialCanvas.SetActive(false);
        PlayerHPUIText.text = string.Empty;
        TutorialProjetileManager.spawnLaser();
        yield return new WaitForSeconds(1f);
        MainGameSceneManage.isTutorialPause = true;
        Time.timeScale = 0;
        TutorialCanvas.SetActive(true);
        TutorialText.text = "There are some Quick/StrongAttack will make from the Boss\nこれはボスによる特殊攻撃です";
        yield return new WaitForSecondsRealtime(4f);
        TutorialText.text = "It will have a yellow warning before it comes\n一部の特殊攻撃前に黄色の警告が表示される";
        yield return new WaitForSecondsRealtime(4f);
        TutorialText.text = "You can use the basic movement to dodge it Or\n移動で回避できるか";
        yield return new WaitForSecondsRealtime(4f);
        TutorialText.text = "Dou can use dashing to dodge it\nダッシュでも回避できる";
        yield return new WaitForSecondsRealtime(4f);
        TutorialText.text = "Dashing:\nFor Keyboard:Space Key\nFor Controller:L2/R2\nダッシュ：キーボード：スペースキー\nコントローラー：L2/R2";
        yield return new WaitForSecondsRealtime(4f);
        TutorialText.text = "During dashing,you have invincibility\nダッシュ中は無敵状態になる";
        yield return new WaitForSecondsRealtime(4f);
        TutorialText.text = "Let's try to dodge it\nさあ、回避を使ってみましょう";
        yield return new WaitForSecondsRealtime(4f);
        Time.timeScale = 1;
        MainGameSceneManage.isTutorialPause = false;
        TutorialCanvas.SetActive(false);
        PlayerMovementTutorial.canMove = true;
        PlayerMovementTutorial.canDash = true;
        TaskText.text = "Task:\nUse Dashing\nタスク：\nダッシュを使う";
        inputText.text = "For Keyboard:Space Key\nFor Controller:L2/R2\nキーボード：スペースキー\nコントローラー：L2/R2";
        yield return new WaitUntil(() => PlayerMovementTutorial.dashed == true);
        TaskBox.SetActive(true);
        yield return new WaitForSeconds(3f);
        TaskBox.SetActive(false);
        TaskText.text = string.Empty;
        inputText.text = string.Empty;
        TutorialCanvas.SetActive(true);
        PlayerMovementTutorial.canMove = false;
        PlayerMovementTutorial.canDash = false;
        Player.transform.position = PlayerMovementTutorial.PlayerOriginposition;
        TutorialText.text = "Great!\n素晴らしい〜";
        yield return new WaitForSeconds(3f);
        TutorialText.text = "Finally,let us talk about Player skill\n最後にプレイヤースキルを説明する";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "Each Charactors have a different skill\nキャラクターごとに異なるスキルがある";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "For example,this charactor can multiple the damage that deal to the Boss during skill active\n例えば、このキャラクターはスキル発動中にボスに与えるダメージを上げることができる";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "For the Skill Input:\nFor Keyboard:Q Key\nFor Controller:● Button\nスキル入力：キーボード：Qキー\nコントローラー：●ボタン";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "Let's try it out\nさあ、スキルを使ってみましょう";
        yield return new WaitForSeconds(3f);
        TutorialCanvas.SetActive(false);
        PlayerMovementTutorial.canMove = true;
        PlayerMovementTutorial.canSkill = true;
        PlayerMovementTutorial.canDash = true;
        TaskText.text = "Task:\nUse Skill\nタスク：\nスキルを使う";
        inputText.text = "For Keyboard:Q Key\nFor Controller:● Button\nキーボード：Qキー\nコントローラー：●ボタン";
        yield return new WaitUntil(() => PlayerMovementTutorial.Skilled == true);
        TaskBox.SetActive(true);
        yield return new WaitForSeconds(6f);
        TaskBox.SetActive(false);
        TaskText.text = string.Empty;
        inputText.text = string.Empty;
        TutorialCanvas.SetActive(true);
        PlayerMovementTutorial.canMove = false;
        PlayerMovementTutorial.canSkill = false;
        PlayerMovementTutorial.canDash = false;
        Player.transform.position = PlayerMovementTutorial.PlayerOriginposition;
        TutorialText.text = "Great!\n素晴らしい〜";
        yield return new WaitForSeconds(3f);
        TutorialText.text = string.Empty;
        PlayerSkillText.text = "Here it will show the cooldown\nActiveSkill/Dashing/PassiveSkill\nここにはクールダウンが表示される\nアクティブスキル/ダッシュ/パッシブスキル";
        yield return new WaitForSeconds(5f);
        PlayerSkillText.text = string.Empty;
        TutorialCanvas.SetActive(false);
        BossManagerTutorial.SpawnClosestWeakPoint();
        yield return new WaitForSeconds(3f);
        TutorialCanvas.SetActive(true);
        TutorialText.text = "Look like we just found a WeakPoint on the Boss\nボスの弱点を発見したようですね";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "During the game,a WeakPoint will spawn at the random position at random time\nゲーム中、ボスの弱点はランダムなタイミング位置で出現する";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "You can get close to the weakpoint and press the button to deal WeakPointDamage\n弱点に近づいて弱点攻撃をすると、\n追加ダメージを与えることができる";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "WeakPoint Button:\nFor Keyboard:Shift Key\nFor Controller:■ Button\n弱点攻撃：キーボード：Shiftキー\nコントローラー：■ボタン";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "Let's try it out\nさあ、弱点攻撃をしてみましょう";
        yield return new WaitForSeconds(3f);
        TutorialCanvas.SetActive(false);
        PlayerMovementTutorial.canMove = true;
        PlayerMovementTutorial.canSkill = true;
        PlayerMovementTutorial.canDash = true;
        TaskText.text = "Task:\nGet close to the Weakpoint\nDeal Weakpoint Damage\nタスク：\n弱点に近づき、弱点ダメージを与える";
        inputText.text = "For Keyboard:shift Key\nFor Controller:■ Button\nキーボード：Shiftキー\nコントローラー：■ボタン";
        yield return new WaitUntil(() => BossManagerTutorial.WeakPointHited == true);
        TaskBox.SetActive(true);
        yield return new WaitForSeconds(3f);
        TaskBox.SetActive(false);
        TaskText.text = string.Empty;
        inputText.text = string.Empty;
        TutorialCanvas.SetActive(true);
        PlayerMovementTutorial.canMove = false;
        PlayerMovementTutorial.canSkill = false;
        PlayerMovementTutorial.canDash = false;
        Player.transform.position = PlayerMovementTutorial.PlayerOriginposition;
        TutorialText.text = "Excellent!\n素晴らしい！";
        yield return new WaitForSeconds(3f);
        TutorialText.text = "That's all for the Tutorial\n以上でチュートリアルは終わりです";
        yield return new WaitForSeconds(4f);
        TutorialText.text = "Let's us Go For The Real Battle!\nさあ、戦いに挑みましょう";
        yield return new WaitForSeconds(3f);
        if (TutorialCheckManager != null)
        {
            TutorialCheckManager.TutorialDone = true;
        }
        SceneManager.LoadScene("CharacterSelectScene");
        yield return null;
    }

    void Update()
    {
        BossHealth = BossManagerTutorial.currentHealth;
    }

    public void Skip()
    {
        if (TutorialCheckManager != null)
        {
            TutorialCheckManager.TutorialDone = true;
        }
        SceneManager.LoadScene("CharacterSelectScene");
    }
}
